//#line 2 "/opt/ros/noetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"
// *********************************************************
//
// File autogenerated for the franka_interactive_controllers package
// by the dynamic_reconfigure package.
// Please do not edit.
//
// ********************************************************/

#ifndef __franka_interactive_controllers__COMPLIANCE_FULL_PARAMCONFIG_H__
#define __franka_interactive_controllers__COMPLIANCE_FULL_PARAMCONFIG_H__

#if __cplusplus >= 201103L
#define DYNAMIC_RECONFIGURE_FINAL final
#else
#define DYNAMIC_RECONFIGURE_FINAL
#endif

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/Group.h>
#include <dynamic_reconfigure/config_init_mutex.h>
#include <boost/any.hpp>

namespace franka_interactive_controllers
{
  class compliance_full_paramConfigStatics;

  class compliance_full_paramConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l,
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }
      virtual ~AbstractParamDescription() = default;

      virtual void clamp(compliance_full_paramConfig &config, const compliance_full_paramConfig &max, const compliance_full_paramConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const compliance_full_paramConfig &config1, const compliance_full_paramConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, compliance_full_paramConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const compliance_full_paramConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, compliance_full_paramConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const compliance_full_paramConfig &config) const = 0;
      virtual void getValue(const compliance_full_paramConfig &config, boost::any &val) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template <class T>
    class ParamDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string a_name, std::string a_type, uint32_t a_level,
          std::string a_description, std::string a_edit_method, T compliance_full_paramConfig::* a_f) :
        AbstractParamDescription(a_name, a_type, a_level, a_description, a_edit_method),
        field(a_f)
      {}

      T compliance_full_paramConfig::* field;

      virtual void clamp(compliance_full_paramConfig &config, const compliance_full_paramConfig &max, const compliance_full_paramConfig &min) const override
      {
        if (config.*field > max.*field)
          config.*field = max.*field;

        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const compliance_full_paramConfig &config1, const compliance_full_paramConfig &config2) const override
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, compliance_full_paramConfig &config) const override
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const compliance_full_paramConfig &config) const override
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, compliance_full_paramConfig &config) const override
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const compliance_full_paramConfig &config) const override
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }

      virtual void getValue(const compliance_full_paramConfig &config, boost::any &val) const override
      {
        val = config.*field;
      }
    };

    class AbstractGroupDescription : public dynamic_reconfigure::Group
    {
      public:
      AbstractGroupDescription(std::string n, std::string t, int p, int i, bool s)
      {
        name = n;
        type = t;
        parent = p;
        state = s;
        id = i;
      }

      virtual ~AbstractGroupDescription() = default;

      std::vector<AbstractParamDescriptionConstPtr> abstract_parameters;
      bool state;

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &config) const =0;
      virtual void updateParams(boost::any &cfg, compliance_full_paramConfig &top) const= 0;
      virtual void setInitialState(boost::any &cfg) const = 0;


      void convertParams()
      {
        for(std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = abstract_parameters.begin(); i != abstract_parameters.end(); ++i)
        {
          parameters.push_back(dynamic_reconfigure::ParamDescription(**i));
        }
      }
    };

    typedef boost::shared_ptr<AbstractGroupDescription> AbstractGroupDescriptionPtr;
    typedef boost::shared_ptr<const AbstractGroupDescription> AbstractGroupDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template<class T, class PT>
    class GroupDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractGroupDescription
    {
    public:
      GroupDescription(std::string a_name, std::string a_type, int a_parent, int a_id, bool a_s, T PT::* a_f) : AbstractGroupDescription(a_name, a_type, a_parent, a_id, a_s), field(a_f)
      {
      }

      GroupDescription(const GroupDescription<T, PT>& g): AbstractGroupDescription(g.name, g.type, g.parent, g.id, g.state), field(g.field), groups(g.groups)
      {
        parameters = g.parameters;
        abstract_parameters = g.abstract_parameters;
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &cfg) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);
        if(!dynamic_reconfigure::ConfigTools::getGroupState(msg, name, (*config).*field))
          return false;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          if(!(*i)->fromMessage(msg, n))
            return false;
        }

        return true;
      }

      virtual void setInitialState(boost::any &cfg) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);
        T* group = &((*config).*field);
        group->state = state;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = boost::any(&((*config).*field));
          (*i)->setInitialState(n);
        }

      }

      virtual void updateParams(boost::any &cfg, compliance_full_paramConfig &top) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);

        T* f = &((*config).*field);
        f->setParams(top, abstract_parameters);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          (*i)->updateParams(n, top);
        }
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &cfg) const override
      {
        const PT config = boost::any_cast<PT>(cfg);
        dynamic_reconfigure::ConfigTools::appendGroup<T>(msg, name, id, parent, config.*field);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          (*i)->toMessage(msg, config.*field);
        }
      }

      T PT::* field;
      std::vector<compliance_full_paramConfig::AbstractGroupDescriptionConstPtr> groups;
    };

class DEFAULT
{
  public:
    DEFAULT()
    {
      state = true;
      name = "Default";
    }

    void setParams(compliance_full_paramConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("x_TRANSLATIONAL_stiffness"==(*_i)->name){x_TRANSLATIONAL_stiffness = boost::any_cast<double>(val);}
        if("y_TRANSLATIONAL_stiffness"==(*_i)->name){y_TRANSLATIONAL_stiffness = boost::any_cast<double>(val);}
        if("z_TRANSLATIONAL_stiffness"==(*_i)->name){z_TRANSLATIONAL_stiffness = boost::any_cast<double>(val);}
        if("x_ROTATIONAL_stiffness"==(*_i)->name){x_ROTATIONAL_stiffness = boost::any_cast<double>(val);}
        if("y_ROTATIONAL_stiffness"==(*_i)->name){y_ROTATIONAL_stiffness = boost::any_cast<double>(val);}
        if("z_ROTATIONAL_stiffness"==(*_i)->name){z_ROTATIONAL_stiffness = boost::any_cast<double>(val);}
        if("all_TRANSLATIONAL_stiffness"==(*_i)->name){all_TRANSLATIONAL_stiffness = boost::any_cast<double>(val);}
        if("all_ROTATIONAL_stiffness"==(*_i)->name){all_ROTATIONAL_stiffness = boost::any_cast<double>(val);}
        if("nullspace_stiffness"==(*_i)->name){nullspace_stiffness = boost::any_cast<double>(val);}
        if("activate_tool_compensation"==(*_i)->name){activate_tool_compensation = boost::any_cast<bool>(val);}
      }
    }

    double x_TRANSLATIONAL_stiffness;
double y_TRANSLATIONAL_stiffness;
double z_TRANSLATIONAL_stiffness;
double x_ROTATIONAL_stiffness;
double y_ROTATIONAL_stiffness;
double z_ROTATIONAL_stiffness;
double all_TRANSLATIONAL_stiffness;
double all_ROTATIONAL_stiffness;
double nullspace_stiffness;
bool activate_tool_compensation;

    bool state;
    std::string name;

    
}groups;



//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double x_TRANSLATIONAL_stiffness;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double y_TRANSLATIONAL_stiffness;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double z_TRANSLATIONAL_stiffness;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double x_ROTATIONAL_stiffness;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double y_ROTATIONAL_stiffness;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double z_ROTATIONAL_stiffness;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double all_TRANSLATIONAL_stiffness;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double all_ROTATIONAL_stiffness;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double nullspace_stiffness;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      bool activate_tool_compensation;
//#line 231 "/opt/ros/noetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();

      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        if ((*i)->fromMessage(msg, *this))
          count++;

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i ++)
      {
        if ((*i)->id == 0)
        {
          boost::any n = boost::any(this);
          (*i)->updateParams(n, *this);
          (*i)->fromMessage(msg, n);
        }
      }

      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("compliance_full_paramConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (size_t i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (size_t i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (size_t i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (size_t i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__, const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toMessage(msg, *this);

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        if((*i)->id == 0)
        {
          (*i)->toMessage(msg, *this);
        }
      }
    }

    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      __toMessage__(msg, __param_descriptions__, __group_descriptions__);
    }

    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      static bool setup=false;

      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->fromServer(nh, *this);

      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++){
        if (!setup && (*i)->id == 0) {
          setup = true;
          boost::any n = boost::any(this);
          (*i)->setInitialState(n);
        }
      }
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const compliance_full_paramConfig &__max__ = __getMax__();
      const compliance_full_paramConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const compliance_full_paramConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->calcLevel(level, config, *this);
      return level;
    }

    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const compliance_full_paramConfig &__getDefault__();
    static const compliance_full_paramConfig &__getMax__();
    static const compliance_full_paramConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    static const std::vector<AbstractGroupDescriptionConstPtr> &__getGroupDescriptions__();

  private:
    static const compliance_full_paramConfigStatics *__get_statics__();
  };

  template <> // Max and min are ignored for strings.
  inline void compliance_full_paramConfig::ParamDescription<std::string>::clamp(compliance_full_paramConfig &config, const compliance_full_paramConfig &max, const compliance_full_paramConfig &min) const
  {
    (void) config;
    (void) min;
    (void) max;
    return;
  }

  class compliance_full_paramConfigStatics
  {
    friend class compliance_full_paramConfig;

    compliance_full_paramConfigStatics()
    {
compliance_full_paramConfig::GroupDescription<compliance_full_paramConfig::DEFAULT, compliance_full_paramConfig> Default("Default", "", 0, 0, true, &compliance_full_paramConfig::groups);
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.x_TRANSLATIONAL_stiffness = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.x_TRANSLATIONAL_stiffness = 400.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.x_TRANSLATIONAL_stiffness = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(compliance_full_paramConfig::AbstractParamDescriptionConstPtr(new compliance_full_paramConfig::ParamDescription<double>("x_TRANSLATIONAL_stiffness", "double", 0, "X-axis Cartesian TRANSLATIONAL stiffness", "", &compliance_full_paramConfig::x_TRANSLATIONAL_stiffness)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(compliance_full_paramConfig::AbstractParamDescriptionConstPtr(new compliance_full_paramConfig::ParamDescription<double>("x_TRANSLATIONAL_stiffness", "double", 0, "X-axis Cartesian TRANSLATIONAL stiffness", "", &compliance_full_paramConfig::x_TRANSLATIONAL_stiffness)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.y_TRANSLATIONAL_stiffness = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.y_TRANSLATIONAL_stiffness = 400.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.y_TRANSLATIONAL_stiffness = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(compliance_full_paramConfig::AbstractParamDescriptionConstPtr(new compliance_full_paramConfig::ParamDescription<double>("y_TRANSLATIONAL_stiffness", "double", 0, "Y-axis Cartesian TRANSLATIONAL stiffness", "", &compliance_full_paramConfig::y_TRANSLATIONAL_stiffness)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(compliance_full_paramConfig::AbstractParamDescriptionConstPtr(new compliance_full_paramConfig::ParamDescription<double>("y_TRANSLATIONAL_stiffness", "double", 0, "Y-axis Cartesian TRANSLATIONAL stiffness", "", &compliance_full_paramConfig::y_TRANSLATIONAL_stiffness)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.z_TRANSLATIONAL_stiffness = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.z_TRANSLATIONAL_stiffness = 400.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.z_TRANSLATIONAL_stiffness = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(compliance_full_paramConfig::AbstractParamDescriptionConstPtr(new compliance_full_paramConfig::ParamDescription<double>("z_TRANSLATIONAL_stiffness", "double", 0, "Z-axis Cartesian TRANSLATIONAL stiffness", "", &compliance_full_paramConfig::z_TRANSLATIONAL_stiffness)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(compliance_full_paramConfig::AbstractParamDescriptionConstPtr(new compliance_full_paramConfig::ParamDescription<double>("z_TRANSLATIONAL_stiffness", "double", 0, "Z-axis Cartesian TRANSLATIONAL stiffness", "", &compliance_full_paramConfig::z_TRANSLATIONAL_stiffness)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.x_ROTATIONAL_stiffness = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.x_ROTATIONAL_stiffness = 30.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.x_ROTATIONAL_stiffness = 5.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(compliance_full_paramConfig::AbstractParamDescriptionConstPtr(new compliance_full_paramConfig::ParamDescription<double>("x_ROTATIONAL_stiffness", "double", 0, "X-axis Cartesian ROTATIONAL stiffness", "", &compliance_full_paramConfig::x_ROTATIONAL_stiffness)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(compliance_full_paramConfig::AbstractParamDescriptionConstPtr(new compliance_full_paramConfig::ParamDescription<double>("x_ROTATIONAL_stiffness", "double", 0, "X-axis Cartesian ROTATIONAL stiffness", "", &compliance_full_paramConfig::x_ROTATIONAL_stiffness)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.y_ROTATIONAL_stiffness = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.y_ROTATIONAL_stiffness = 30.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.y_ROTATIONAL_stiffness = 5.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(compliance_full_paramConfig::AbstractParamDescriptionConstPtr(new compliance_full_paramConfig::ParamDescription<double>("y_ROTATIONAL_stiffness", "double", 0, "Y-axis Cartesian ROTATIONAL stiffness", "", &compliance_full_paramConfig::y_ROTATIONAL_stiffness)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(compliance_full_paramConfig::AbstractParamDescriptionConstPtr(new compliance_full_paramConfig::ParamDescription<double>("y_ROTATIONAL_stiffness", "double", 0, "Y-axis Cartesian ROTATIONAL stiffness", "", &compliance_full_paramConfig::y_ROTATIONAL_stiffness)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.z_ROTATIONAL_stiffness = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.z_ROTATIONAL_stiffness = 30.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.z_ROTATIONAL_stiffness = 5.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(compliance_full_paramConfig::AbstractParamDescriptionConstPtr(new compliance_full_paramConfig::ParamDescription<double>("z_ROTATIONAL_stiffness", "double", 0, "Z-axis Cartesian ROTATIONAL stiffness", "", &compliance_full_paramConfig::z_ROTATIONAL_stiffness)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(compliance_full_paramConfig::AbstractParamDescriptionConstPtr(new compliance_full_paramConfig::ParamDescription<double>("z_ROTATIONAL_stiffness", "double", 0, "Z-axis Cartesian ROTATIONAL stiffness", "", &compliance_full_paramConfig::z_ROTATIONAL_stiffness)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.all_TRANSLATIONAL_stiffness = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.all_TRANSLATIONAL_stiffness = 400.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.all_TRANSLATIONAL_stiffness = 200.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(compliance_full_paramConfig::AbstractParamDescriptionConstPtr(new compliance_full_paramConfig::ParamDescription<double>("all_TRANSLATIONAL_stiffness", "double", 0, "Cartesian TRANSLATIONAL stiffness", "", &compliance_full_paramConfig::all_TRANSLATIONAL_stiffness)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(compliance_full_paramConfig::AbstractParamDescriptionConstPtr(new compliance_full_paramConfig::ParamDescription<double>("all_TRANSLATIONAL_stiffness", "double", 0, "Cartesian TRANSLATIONAL stiffness", "", &compliance_full_paramConfig::all_TRANSLATIONAL_stiffness)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.all_ROTATIONAL_stiffness = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.all_ROTATIONAL_stiffness = 30.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.all_ROTATIONAL_stiffness = 10.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(compliance_full_paramConfig::AbstractParamDescriptionConstPtr(new compliance_full_paramConfig::ParamDescription<double>("all_ROTATIONAL_stiffness", "double", 0, "Cartesian ROTATIONAL stiffness", "", &compliance_full_paramConfig::all_ROTATIONAL_stiffness)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(compliance_full_paramConfig::AbstractParamDescriptionConstPtr(new compliance_full_paramConfig::ParamDescription<double>("all_ROTATIONAL_stiffness", "double", 0, "Cartesian ROTATIONAL stiffness", "", &compliance_full_paramConfig::all_ROTATIONAL_stiffness)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.nullspace_stiffness = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.nullspace_stiffness = 100.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.nullspace_stiffness = 0.5;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(compliance_full_paramConfig::AbstractParamDescriptionConstPtr(new compliance_full_paramConfig::ParamDescription<double>("nullspace_stiffness", "double", 0, "Stiffness of the joint space nullspace controller (the desired configuration is the one at startup)", "", &compliance_full_paramConfig::nullspace_stiffness)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(compliance_full_paramConfig::AbstractParamDescriptionConstPtr(new compliance_full_paramConfig::ParamDescription<double>("nullspace_stiffness", "double", 0, "Stiffness of the joint space nullspace controller (the desired configuration is the one at startup)", "", &compliance_full_paramConfig::nullspace_stiffness)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.activate_tool_compensation = 0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.activate_tool_compensation = 1;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.activate_tool_compensation = 1;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(compliance_full_paramConfig::AbstractParamDescriptionConstPtr(new compliance_full_paramConfig::ParamDescription<bool>("activate_tool_compensation", "bool", 0, "trigger to activate external tool compensation (the desired compensation forces defined in ./config)", "", &compliance_full_paramConfig::activate_tool_compensation)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(compliance_full_paramConfig::AbstractParamDescriptionConstPtr(new compliance_full_paramConfig::ParamDescription<bool>("activate_tool_compensation", "bool", 0, "trigger to activate external tool compensation (the desired compensation forces defined in ./config)", "", &compliance_full_paramConfig::activate_tool_compensation)));
//#line 247 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.convertParams();
//#line 247 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(compliance_full_paramConfig::AbstractGroupDescriptionConstPtr(new compliance_full_paramConfig::GroupDescription<compliance_full_paramConfig::DEFAULT, compliance_full_paramConfig>(Default)));
//#line 369 "/opt/ros/noetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

      for (std::vector<compliance_full_paramConfig::AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        __description_message__.groups.push_back(**i);
      }
      __max__.__toMessage__(__description_message__.max, __param_descriptions__, __group_descriptions__);
      __min__.__toMessage__(__description_message__.min, __param_descriptions__, __group_descriptions__);
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__, __group_descriptions__);
    }
    std::vector<compliance_full_paramConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    std::vector<compliance_full_paramConfig::AbstractGroupDescriptionConstPtr> __group_descriptions__;
    compliance_full_paramConfig __max__;
    compliance_full_paramConfig __min__;
    compliance_full_paramConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;

    static const compliance_full_paramConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static compliance_full_paramConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &compliance_full_paramConfig::__getDescriptionMessage__()
  {
    return __get_statics__()->__description_message__;
  }

  inline const compliance_full_paramConfig &compliance_full_paramConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }

  inline const compliance_full_paramConfig &compliance_full_paramConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }

  inline const compliance_full_paramConfig &compliance_full_paramConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }

  inline const std::vector<compliance_full_paramConfig::AbstractParamDescriptionConstPtr> &compliance_full_paramConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const std::vector<compliance_full_paramConfig::AbstractGroupDescriptionConstPtr> &compliance_full_paramConfig::__getGroupDescriptions__()
  {
    return __get_statics__()->__group_descriptions__;
  }

  inline const compliance_full_paramConfigStatics *compliance_full_paramConfig::__get_statics__()
  {
    const static compliance_full_paramConfigStatics *statics;

    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = compliance_full_paramConfigStatics::get_instance();

    return statics;
  }


}

#undef DYNAMIC_RECONFIGURE_FINAL

#endif // __COMPLIANCE_FULL_PARAMRECONFIGURATOR_H__
