// Generated by gencpp from file record_ros/String_cmd.msg
// DO NOT EDIT!


#ifndef RECORD_ROS_MESSAGE_STRING_CMD_H
#define RECORD_ROS_MESSAGE_STRING_CMD_H

#include <ros/service_traits.h>


#include <record_ros/String_cmdRequest.h>
#include <record_ros/String_cmdResponse.h>


namespace record_ros
{

struct String_cmd
{

typedef String_cmdRequest Request;
typedef String_cmdResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct String_cmd
} // namespace record_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::record_ros::String_cmd > {
  static const char* value()
  {
    return "d4463b49bd5bb77dbd8c4356f5dc1c28";
  }

  static const char* value(const ::record_ros::String_cmd&) { return value(); }
};

template<>
struct DataType< ::record_ros::String_cmd > {
  static const char* value()
  {
    return "record_ros/String_cmd";
  }

  static const char* value(const ::record_ros::String_cmd&) { return value(); }
};


// service_traits::MD5Sum< ::record_ros::String_cmdRequest> should match
// service_traits::MD5Sum< ::record_ros::String_cmd >
template<>
struct MD5Sum< ::record_ros::String_cmdRequest>
{
  static const char* value()
  {
    return MD5Sum< ::record_ros::String_cmd >::value();
  }
  static const char* value(const ::record_ros::String_cmdRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::record_ros::String_cmdRequest> should match
// service_traits::DataType< ::record_ros::String_cmd >
template<>
struct DataType< ::record_ros::String_cmdRequest>
{
  static const char* value()
  {
    return DataType< ::record_ros::String_cmd >::value();
  }
  static const char* value(const ::record_ros::String_cmdRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::record_ros::String_cmdResponse> should match
// service_traits::MD5Sum< ::record_ros::String_cmd >
template<>
struct MD5Sum< ::record_ros::String_cmdResponse>
{
  static const char* value()
  {
    return MD5Sum< ::record_ros::String_cmd >::value();
  }
  static const char* value(const ::record_ros::String_cmdResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::record_ros::String_cmdResponse> should match
// service_traits::DataType< ::record_ros::String_cmd >
template<>
struct DataType< ::record_ros::String_cmdResponse>
{
  static const char* value()
  {
    return DataType< ::record_ros::String_cmd >::value();
  }
  static const char* value(const ::record_ros::String_cmdResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RECORD_ROS_MESSAGE_STRING_CMD_H
