<?xml version="1.0"?>
<package format="2">
  <name>TPGPT_two_args</name>
  <version>0.0.1</version>
  <description>The reshelving_policy_transport package</description>

  <maintainer email="ravi@todo.todo">ravi</maintainer>
  <license>TODO</license>

  <buildtool_depend>catkin</buildtool_depend>

  <depend>rospy</depend>
  <depend>geometry_msgs</depend>
  <depend>tf2_ros</depend>
  <depend>std_msgs</depend>

  <exec_depend>python3-numpy</exec_depend>
  <exec_depend>python3-scipy</exec_depend>
  <exec_depend>python3-scikit-learn</exec_depend>

  <export>
    </export>
</package>
